
version: '3.1'

services:
  db:
    restart: always
    image: mysql:5.7
    ports:
        - "3306:3306"
    environment:
        MYSQL_USER: 'docker'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
        MYSQL_DATABASE: 'docker_db'
    volumes:
        - dbdata:/var/lib/mysql
        - ./docker/sql:/docker-entrypoint-initdb.d
volumes:
  dbdata:
      driver: local